name: Run JMeter Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  run-jmeter-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JMeter
        run: |
          wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xvzf apache-jmeter-5.6.3.tgz
          sudo mv apache-jmeter-5.6.3 /opt/jmeter
          sudo ln -s /opt/jmeter/bin/jmeter /usr/local/bin/jmeter

      - name: Run JMeter Tests
        run: |
          jmeter -n -t jmeter-tests/Test\ Plan\ South.jmx -l results/results.jtl
          ls -l results

      - name: Generate Report
        run: |
          jmeter -g results/results.jtl -o results/jmeter-report

      - name: List report results
        run: |
          ls -l results/jmeter-report

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: JMeter Test Report
          path: results/jmeter-report

      - name: Set up Git credentials
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/luanfreitasqa/testes-south-jmeter.git

      - name: Publish report to gh-pages
        run: |
          git fetch origin
          git checkout gh-pages
          cp -r results/jmeter-report/* .
          git add .
          git commit -m "Atualizando relat√≥rios do JMeter"
          git push origin gh-pages